
#!/bin/bash
#$ -N randombyamino
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-100:1
#$ -pe serial 15


source ~/.bash_profile

CPU=15 # doesn't matter for paml
NUM=`expr $SGE_TASK_ID - 1` # index from 0
FINALFILE=mutsel-$JOB_NAME.txt

# Set up directories
SIMDIR=/home/sjs3495/MutSel/Simulator
THINGSDIR=/home/sjs3495/MutSel/mutsel_for_cluster
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID
RDIR=/home/sjs3495/$JOB_NAME-$JOB_ID

mkdir -p $RDIR
mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi

cd $WDIR

# Copy files
cp -r $SIMDIR .
cp $THINGSDIR/*.py .
cp $THINGSDIR/hrh1_aa.fasta .
cp $THINGSDIR/100.tre tree.tre

# cp hyphy
cp $THINGSDIR/hyphy_files/* .
cp /home/sjs3495/bin/bin/HYPHYMP .

# cp paml
#cp $THINGSDIR/codeml.ctl .
#cp /home/sjs3495/bin/codeml .

# Run
module load python
python simulate_and_infer_cluster.py $CPU $NUM tree.tre $RDIR $FINALFILE

# Cleanup
cp *.fasta $RDIR
cp mutsel_* $RDIR
rm -rf $WDIR
