
#!/bin/bash
#$ -N siminf
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-123:1
#$ -pe serial 5


source ~/.bash_profile

CPU=5
NUM=`expr $SGE_TASK_ID - 1` # index from 0
FINALFILE='mutsel_results.txt'

# Set up directories
SIMDIR=/home/sjs3495/MutSel/Simulator
THINGSDIR=/home/sjs3495/MutSel/mutsel_for_cluster
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID
RDIR=/home/sjs3495/$JOB_NAME-$JOB_ID

mkdir -p $RDIR
mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi

cd $WDIR

# Copy files
cp -r $SIMDIR .
cp $THINGSDIR/*.py .
cp $THINGSDIR/hrh1_aa.fasta .
cp $THINGSDIR/2.tre .
cp $THINGSDIR/hyphy_files/* .
cp /home/sjs3495/bin/bin/HYPHYMP .

# Run
module load python
python simulate_and_infer_cluster.py $CPU $NUM $RDIR $FINALFILE

# Cleanup
rm -rf $WDIR
